services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Define two listeners: INTERNAL (for Docker) and EXTERNAL (for Python)
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    # NEW: Persistent storage for Kafka logs
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
    depends_on:
      - broker
  
  spark-stream:
    image: apache/spark:latest
    container_name: spark-stream
    user: root
    depends_on:
      - broker
    env_file:
      - .env
    volumes:
      - .:/opt/spark/work-dir
      - ./checkpoints:/opt/spark/checkpoints
    ports:
      - "4040:4040"
    working_dir: /opt/spark/work-dir
    command: >
      /opt/spark/bin/spark-submit
      --master local[*]
      --driver-memory 1g
      --conf spark.driver.bindAddress=0.0.0.0
      --conf spark.sql.shuffle.partitions=1
      --conf spark.sql.streaming.checkpointLocation=/opt/spark/checkpoints
      --packages net.snowflake:spark-snowflake_2.13:3.1.8,net.snowflake:snowflake-jdbc:3.16.1,org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.1
      /opt/spark/work-dir/Consumer/spark_consumer.py


volumes:
  kafka_data:
