CREATE OR REPLACE TASK LEARNING.PUBLIC.CLEAN_USERS_CDC_STAGING
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = '1 MINUTE'
AS
MERGE INTO LEARNING.PUBLIC.USERS_CDC_CURATED t
USING (
    SELECT *
    FROM LEARNING.PUBLIC.USERS_CDC_STAGING
    QUALIFY ROW_NUMBER() OVER (PARTITION BY lsn_num ORDER BY lsn_num) = 1
) s
ON t.lsn_num = s.lsn_num
WHEN NOT MATCHED THEN
  INSERT (action, id, name, email, updated_at, lsn_num)
  VALUES (s.action, s.id, s.name, s.email, s.updated_at, s.lsn_num);

CREATE OR REPLACE TASK LEARNING.PUBLIC.TRUNCATE_USERS_CDC_STAGING
  WAREHOUSE = COMPUTE_WH
  AFTER LEARNING.PUBLIC.CLEAN_USERS_CDC_STAGING
AS
TRUNCATE TABLE LEARNING.PUBLIC.USERS_CDC_STAGING;